-- ============================================================
-- Generated by scripts/generate-seed.mts — do not hand-edit.
-- Source: src/lib/subjects/*
-- ============================================================

insert into subjects (id, title, description, icon, sort_order) values (
  'chemistry', 'Chemistry', 'S.4 industrial processes — an 8-day revision sprint.', 'bi-thermometer-half', 0
)
on conflict (id) do update set title = excluded.title, description = excluded.description, icon = excluded.icon, sort_order = excluded.sort_order;

insert into topics (id, subject_id, day, title, token_reward_base, raw_materials, steps, equations, side_effects, social_benefits, flashcards, content) values (
  'oxygen', 'chemistry', 1, 'Manufacture of Oxygen', 5,
  '{"Air","Concentrated sodium hydroxide","Silica"}', '{"Air is passed through an air filter to remove dust and smoke particles.","Air is passed through concentrated sodium hydroxide solution to remove carbon dioxide.","Air is passed through silica to absorb water vapour.","CO2 and water vapour are removed before liquefaction because they would solidify and block the apparatus.","The remaining air is compressed at 200 atmospheres and cooled to about -200°C to form liquid air.","Liquid air is fractionally distilled in a fractionating column.","Nitrogen boils off first (b.p. -196°C), leaving oxygen (b.p. -183°C) behind.","Pure oxygen is stored under pressure in steel cylinders."}', '{"2NaOH(aq) + CO2(g) → Na2CO3(aq) + H2O(l)"}',
  '[{"issue":"Explosion of oxygen cylinders due to high pressure.","effect":"Can ignite nearby materials, causing injury and fire outbreaks.","mitigation":"Regular maintenance and monitoring of cylinders; store in cool areas."},{"issue":"Exposure to liquid oxygen.","effect":"Severe skin/eye irritation, burns, loss of vision, cancer.","mitigation":"Post hazard warnings; communicate safety info to workers; submerge affected skin in warm water."}]'::jsonb, '{"Employment opportunities → improved income → better standards of living","Increased government revenue from taxes → improved infrastructure (roads, schools, hospitals)","Development of small-scale businesses around the plant","Availability of oxygen for patients → saves lives"}', '[{"front":"Why are CO2 and water vapour removed before air is liquefied?","back":"Because they would solidify and block the apparatus."},{"front":"Which gas boils off first during fractional distillation of liquid air, and why?","back":"Nitrogen, because it has a lower boiling point (-196°C) than oxygen (-183°C)."},{"front":"What removes CO2 from air in this process?","back":"Concentrated sodium hydroxide solution."},{"front":"What absorbs water vapour from the air?","back":"Silica."},{"front":"At what pressure and temperature is air liquefied?","back":"200 atmospheres, cooled to about -200°C."}]'::jsonb, '{}'::jsonb
)
on conflict (id) do update set
  subject_id = excluded.subject_id, day = excluded.day, title = excluded.title,
  token_reward_base = excluded.token_reward_base, raw_materials = excluded.raw_materials,
  steps = excluded.steps, equations = excluded.equations, side_effects = excluded.side_effects,
  social_benefits = excluded.social_benefits, flashcards = excluded.flashcards, content = excluded.content;

delete from quiz_questions where topic_id = 'oxygen';

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'oxygen', 'Why must carbon dioxide be removed from air before liquefaction?', 'multiple_choice',
  '{"It reacts with nitrogen","It would solidify and block the apparatus","It lowers the boiling point of oxygen","It is flammable"}', 1,
  null, null, 'CO2 (and water vapour) solidify at the very low temperatures used and would block the plant.'
);

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'oxygen', 'What is the correct order in which nitrogen and oxygen separate during fractional distillation of liquid air?', 'multiple_choice',
  '{"Oxygen boils off first, then nitrogen","Nitrogen boils off first, then oxygen","Both boil off at the same time","Neither boils; they are filtered"}', 1,
  null, null, 'Nitrogen has a lower boiling point (-196°C) than oxygen (-183°C), so it boils off first.'
);

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'oxygen', 'Which substance is used to remove carbon dioxide from air in this process?', 'multiple_choice',
  '{"Silica","Concentrated sodium hydroxide","Calcium oxide","Sodium chloride"}', 1,
  null, null, '2NaOH(aq) + CO2(g) → Na2CO3(aq) + H2O(l).'
);

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'oxygen', 'A major danger during storage of manufactured oxygen is:', 'multiple_choice',
  '{"Explosion of cylinders due to high pressure","Oxygen turning into ozone spontaneously","Oxygen reacting with the steel cylinder","Oxygen leaking as a liquid at room temperature"}', 0,
  null, null, 'High-pressure storage risks explosion; mitigated by regular maintenance and monitoring.'
);

insert into topics (id, subject_id, day, title, token_reward_base, raw_materials, steps, equations, side_effects, social_benefits, flashcards, content) values (
  'sulphuric-acid', 'chemistry', 2, 'Manufacture of Sulphuric Acid (Contact Process)', 5,
  '{"Dry sulphur dioxide","Dry oxygen","Vanadium(V) oxide catalyst","Water"}', '{"Dry SO2 and dry O2, free from impurities, are heated to about 450°C at low pressure (~1 atmosphere) in a combustion cylinder with a V2O5 catalyst, forming sulphur trioxide.","Sulphur trioxide is dissolved in concentrated sulphuric acid to form a fuming liquid called oleum.","Oleum is added to a regulated volume of distilled water to form 98% concentrated sulphuric acid."}', '{"2SO2(g) + O2(g) ⇌ 2SO3(g)  [V2O5 catalyst, ~450°C]"}',
  '[{"issue":"Hot surface burns from combustion cylinders.","effect":"Wounds and pain to workers.","mitigation":"Proper use of personal protective equipment (PPE)."},{"issue":"Poisonous waste gas fumes.","effect":"Respiratory complications when inhaled.","mitigation":"Fit catalytic converters in exhaust pipes."},{"issue":"Destruction of vegetation for plant construction.","effect":"Increased CO2 in the air, contributing to global warming.","mitigation":"Plant fast-growing, fast-maturing trees."}]'::jsonb, '{"Employment opportunities → increased income → improved standards of living","Government revenue → roads → facilitates trade","Government revenue → schools → better, cheaper education"}', '[{"front":"What catalyst is used in the Contact Process?","back":"Vanadium(V) oxide, V2O5."},{"front":"What is oleum?","back":"A fuming liquid formed when SO3 is dissolved in concentrated sulphuric acid."},{"front":"At roughly what temperature is SO2 oxidised to SO3?","back":"About 450°C."},{"front":"How is 98% concentrated sulphuric acid finally obtained?","back":"By adding oleum to a regulated volume of distilled water."}]'::jsonb, '{}'::jsonb
)
on conflict (id) do update set
  subject_id = excluded.subject_id, day = excluded.day, title = excluded.title,
  token_reward_base = excluded.token_reward_base, raw_materials = excluded.raw_materials,
  steps = excluded.steps, equations = excluded.equations, side_effects = excluded.side_effects,
  social_benefits = excluded.social_benefits, flashcards = excluded.flashcards, content = excluded.content;

delete from quiz_questions where topic_id = 'sulphuric-acid';

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'sulphuric-acid', 'Which catalyst is used to convert sulphur dioxide to sulphur trioxide?', 'multiple_choice',
  '{"Iron","Vanadium(V) oxide","Platinum","Manganese(IV) oxide"}', 1,
  null, null, 'V2O5 is the catalyst used in the Contact Process at around 450°C.'
);

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'sulphuric-acid', 'Why is SO3 dissolved in concentrated sulphuric acid rather than water directly?', 'multiple_choice',
  '{"Dissolving SO3 directly in water causes a violent, uncontrollable reaction","Water does not dissolve SO3 at all","It produces a coloured product","It is cheaper"}', 0,
  null, null, 'SO3 is instead absorbed to form oleum, which is then carefully diluted with water.'
);

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'sulphuric-acid', 'How is poisonous waste gas from this process typically mitigated?', 'multiple_choice',
  '{"Releasing it at night","Fitting catalytic converters in exhaust pipes","Diluting it with fresh air only","Storing it underground"}', 1,
  null, null, 'Catalytic converters reduce harmful gases before they reach the atmosphere.'
);

insert into topics (id, subject_id, day, title, token_reward_base, raw_materials, steps, equations, side_effects, social_benefits, flashcards, content) values (
  'ethanol', 'chemistry', 2, 'Manufacture of Ethanol', 5,
  '{"Starch-containing substance","Malt (diastase enzyme)","Yeast (maltase, zymase enzymes)"}', '{"The starch-containing substance is crushed to extract starch.","Malt is added to the starch; diastase in malt catalyses hydrolysis of starch to maltose.","Yeast is added to the maltose after about 5 days at room temperature.","Maltase in yeast catalyses hydrolysis of maltose to glucose.","Zymase in yeast catalyses breakdown of glucose to crude ethanol and carbon dioxide.","Crude ethanol is converted to pure ethanol by fractional distillation."}', '{"(C6H10O5)n + nH2O → nC12H22O11 (starch → maltose, diastase)","C12H22O11 + H2O → 2C6H12O6 (maltose → glucose, maltase)","C6H12O6 → 2C2H5OH + 2CO2 (glucose → ethanol, zymase)"}',
  '[{"issue":"Hot surface burns from the distillation tank.","effect":"Wounds and pain to workers.","mitigation":"Proper use of PPE."},{"issue":"Destruction of vegetation for plant construction.","effect":"Increased CO2, contributing to global warming.","mitigation":"Plant fast-growing, fast-maturing trees."}]'::jsonb, '{"Employment opportunities → increased income → improved standards of living","Government revenue → roads, schools, hospitals"}', '[{"front":"What enzyme in malt converts starch to maltose?","back":"Diastase."},{"front":"What enzyme in yeast converts maltose to glucose?","back":"Maltase."},{"front":"What enzyme in yeast breaks down glucose to ethanol?","back":"Zymase."},{"front":"How is crude ethanol purified?","back":"By fractional distillation."}]'::jsonb, '{}'::jsonb
)
on conflict (id) do update set
  subject_id = excluded.subject_id, day = excluded.day, title = excluded.title,
  token_reward_base = excluded.token_reward_base, raw_materials = excluded.raw_materials,
  steps = excluded.steps, equations = excluded.equations, side_effects = excluded.side_effects,
  social_benefits = excluded.social_benefits, flashcards = excluded.flashcards, content = excluded.content;

delete from quiz_questions where topic_id = 'ethanol';

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'ethanol', 'Which enzyme catalyses the hydrolysis of starch to maltose?', 'multiple_choice',
  '{"Zymase","Diastase","Maltase","Amylase-2"}', 1,
  null, null, 'Diastase, present in malt, hydrolyses starch to maltose.'
);

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'ethanol', 'Zymase catalyses the conversion of:', 'multiple_choice',
  '{"Starch to maltose","Maltose to glucose","Glucose to ethanol and carbon dioxide","Ethanol to acetic acid"}', 2,
  null, null, 'Zymase in yeast breaks glucose down into ethanol and CO2 (fermentation).'
);

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'ethanol', 'How is pure ethanol obtained from the fermentation mixture?', 'multiple_choice',
  '{"Filtration","Fractional distillation","Precipitation","Electrolysis"}', 1,
  null, null, 'Fractional distillation separates ethanol from water and other impurities by boiling point.'
);

insert into topics (id, subject_id, day, title, token_reward_base, raw_materials, steps, equations, side_effects, social_benefits, flashcards, content) values (
  'detergents', 'chemistry', 3, 'Manufacture of Detergent (Soap)', 5,
  '{"Vegetable oil","Concentrated sodium hydroxide","Sodium chloride (brine)"}', '{"Vegetable oil and concentrated sodium hydroxide are boiled together, with stirring, until no more reaction occurs, in a stainless-steel boiler.","The soap solution is cooled; concentrated sodium chloride solution is added to precipitate the soap (salting out).","Soap floats and is skimmed off; perfumes and dyes may be added.","It is purified by re-boiling in water and re-precipitating with brine.","Soap is baked into desired bars and stored."}', '{"Fat/Oil + 3NaOH → Glycerol + 3 Soap (saponification)"}',
  '[{"issue":"Hot surface burns during heating.","effect":"Wounds and pain to workers.","mitigation":"Proper use of PPE."},{"issue":"Destruction of vegetation for plant construction.","effect":"Increased CO2, global warming.","mitigation":"Plant fast-growing, fast-maturing trees."}]'::jsonb, '{"Employment → increased income → improved standards of living","Government revenue → roads, schools, hospitals"}', '[{"front":"What process converts oil + NaOH into soap?","back":"Saponification."},{"front":"What is added to soap solution to precipitate the soap?","back":"Concentrated sodium chloride solution (brine) — ''salting out''."},{"front":"What is the by-product of saponification, alongside soap?","back":"Glycerol."}]'::jsonb, '{}'::jsonb
)
on conflict (id) do update set
  subject_id = excluded.subject_id, day = excluded.day, title = excluded.title,
  token_reward_base = excluded.token_reward_base, raw_materials = excluded.raw_materials,
  steps = excluded.steps, equations = excluded.equations, side_effects = excluded.side_effects,
  social_benefits = excluded.social_benefits, flashcards = excluded.flashcards, content = excluded.content;

delete from quiz_questions where topic_id = 'detergents';

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'detergents', 'The reaction between vegetable oil and concentrated sodium hydroxide to form soap is called:', 'multiple_choice',
  '{"Esterification","Saponification","Neutralisation","Fermentation"}', 1,
  null, null, 'Saponification produces soap and glycerol.'
);

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'detergents', 'What is added to the cooled soap solution to precipitate the soap out?', 'multiple_choice',
  '{"Distilled water","Concentrated sodium chloride solution","Dilute sulphuric acid","Silica"}', 1,
  null, null, 'Brine (concentrated NaCl solution) ''salts out'' the soap so it floats and can be skimmed off.'
);

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'detergents', 'What is the by-product of soap manufacture, besides soap itself?', 'multiple_choice',
  '{"Glycerol","Ammonia","Oleum","Cryolite"}', 0,
  null, null, 'Saponification of fats/oils with NaOH produces soap and glycerol.'
);

insert into topics (id, subject_id, day, title, token_reward_base, raw_materials, steps, equations, side_effects, social_benefits, flashcards, content) values (
  'iron', 'chemistry', 3, 'Extraction of Iron (Blast Furnace)', 5,
  '{"Coke","Haematite (iron ore)","Limestone","Hot air"}', '{"Coke, haematite and limestone are fed into a blast furnace from the top; hot air enters from the bottom.","Coke is oxidised by hot air to carbon dioxide.","Carbon dioxide is reduced by unreacted coke to carbon monoxide.","Carbon monoxide reduces haematite to molten iron, releasing carbon dioxide.","Limestone decomposes to calcium oxide and carbon dioxide.","Calcium oxide reacts with silicon dioxide impurity to form calcium silicate (slag), which is tapped off."}', '{"2C(s) + O2(g) → 2CO(g)","Fe2O3(s) + 3CO(g) → 2Fe(l) + 3CO2(g)","CaCO3(s) → CaO(s) + CO2(g)","CaO(s) + SiO2(s) → CaSiO3(l) (slag)"}',
  '[{"issue":"Hot surface burns during the process.","effect":"Wounds and pain to workers.","mitigation":"Proper use of PPE."},{"issue":"Destruction of vegetation for plant construction.","effect":"Increased CO2, global warming.","mitigation":"Plant fast-growing, fast-maturing trees."}]'::jsonb, '{"Employment → increased income → improved standards of living","Government revenue → roads, schools, hospitals"}', '[{"front":"What reduces haematite to molten iron in the blast furnace?","back":"Carbon monoxide."},{"front":"What is the role of limestone in iron extraction?","back":"It decomposes to CaO, which reacts with silica impurity to form slag (calcium silicate), removing it."},{"front":"What is the main iron ore mentioned in this process?","back":"Haematite."}]'::jsonb, '{}'::jsonb
)
on conflict (id) do update set
  subject_id = excluded.subject_id, day = excluded.day, title = excluded.title,
  token_reward_base = excluded.token_reward_base, raw_materials = excluded.raw_materials,
  steps = excluded.steps, equations = excluded.equations, side_effects = excluded.side_effects,
  social_benefits = excluded.social_benefits, flashcards = excluded.flashcards, content = excluded.content;

delete from quiz_questions where topic_id = 'iron';

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'iron', 'What reduces iron(III) oxide to molten iron in the blast furnace?', 'multiple_choice',
  '{"Coke directly","Carbon monoxide","Hot air","Limestone"}', 1,
  null, null, 'Fe2O3(s) + 3CO(g) → 2Fe(l) + 3CO2(g).'
);

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'iron', 'Why is limestone added to the blast furnace?', 'multiple_choice',
  '{"To provide the iron itself","To react with silica impurity and form slag","To cool the furnace","To act as the fuel"}', 1,
  null, null, 'CaO from decomposed limestone reacts with SiO2 to form calcium silicate (slag), removing the impurity.'
);

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'iron', 'What is produced when coke is oxidised by hot air at the bottom of the furnace?', 'multiple_choice',
  '{"Carbon monoxide directly","Carbon dioxide","Calcium oxide","Silicon dioxide"}', 1,
  null, null, 'Coke is first oxidised to CO2, which is then reduced by more coke to CO.'
);

insert into topics (id, subject_id, day, title, token_reward_base, raw_materials, steps, equations, side_effects, social_benefits, flashcards, content) values (
  'copper', 'chemistry', 4, 'Extraction of Copper', 5,
  '{"Copper pyrites","Silicon dioxide","Air"}', '{"Copper pyrites are crushed and concentrated by froth flotation.","The concentrated ore is dried and roasted in air to form copper(I) sulphide, iron(II) oxide, and sulphur dioxide gas.","Silicon dioxide is added; it reacts with iron(II) oxide to form iron(II) silicate, removing the iron oxide as slag.","The remaining copper(I) sulphide is heated in a controlled air supply to form impure copper.","Impure copper is purified by electrolysis in an electrolytic cell to form pure copper."}', '{"FeO + SiO2 → FeSiO3 (slag)"}',
  '[{"issue":"Destruction of vegetation for plant construction.","effect":"Increased CO2, global warming.","mitigation":"Plant fast-growing, fast-maturing trees."},{"issue":"Toxic sulphur dioxide released to the atmosphere.","effect":"Respiratory complications.","mitigation":"Fit scrubbers in exhaust pipes to neutralise acidic gases."}]'::jsonb, '{"Employment → increased income → improved standards of living","Government revenue → roads, schools, hospitals"}', '[{"front":"How is copper pyrites first concentrated?","back":"By froth flotation."},{"front":"What removes iron(II) oxide during copper extraction?","back":"Silicon dioxide, forming iron(II) silicate slag."},{"front":"How is impure copper finally purified?","back":"By electrolysis in an electrolytic cell."}]'::jsonb, '{}'::jsonb
)
on conflict (id) do update set
  subject_id = excluded.subject_id, day = excluded.day, title = excluded.title,
  token_reward_base = excluded.token_reward_base, raw_materials = excluded.raw_materials,
  steps = excluded.steps, equations = excluded.equations, side_effects = excluded.side_effects,
  social_benefits = excluded.social_benefits, flashcards = excluded.flashcards, content = excluded.content;

delete from quiz_questions where topic_id = 'copper';

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'copper', 'What method is used to concentrate copper pyrites before roasting?', 'multiple_choice',
  '{"Fractional distillation","Froth flotation","Electrolysis","Filtration"}', 1,
  null, null, 'Froth flotation separates the valuable ore from waste rock.'
);

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'copper', 'What is added to remove iron(II) oxide during roasting?', 'multiple_choice',
  '{"Limestone","Silicon dioxide","Sodium hydroxide","Cryolite"}', 1,
  null, null, 'SiO2 reacts with FeO to form iron(II) silicate slag, which is removed.'
);

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'copper', 'How is impure copper converted into pure copper?', 'multiple_choice',
  '{"Roasting again","Electrolysis","Froth flotation","Distillation"}', 1,
  null, null, 'Electrolytic refining deposits pure copper at the cathode.'
);

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'copper', 'A key toxic gas released during copper extraction, requiring scrubbers, is:', 'multiple_choice',
  '{"Carbon monoxide","Sulphur dioxide","Ammonia","Chlorine"}', 1,
  null, null, 'SO2 from roasting causes respiratory problems and acid rain if unmitigated.'
);

insert into topics (id, subject_id, day, title, token_reward_base, raw_materials, steps, equations, side_effects, social_benefits, flashcards, content) values (
  'aluminium', 'chemistry', 4, 'Extraction of Aluminium', 5,
  '{"Bauxite","Sodium hydroxide","Cryolite"}', '{"Bauxite is roasted in air to drive off water, then crushed into fine powder.","It is concentrated with hot sodium hydroxide solution (Bayer''s process) to form aluminium hydroxide.","Aluminium hydroxide is heated to form pure aluminium oxide (alumina).","Aluminium oxide is dissolved in molten cryolite to lower its melting point to about 800°C.","The molten mixture is electrolysed between graphite electrodes.","At the cathode, aluminium ions are reduced and discharged as molten aluminium metal.","At the anode, oxide ions are oxidised and released as oxygen gas."}', '{"Al2O3(s) + 2OH-(aq) → 2AlO2-(aq) + H2O(l)","Cathode: Al3+(l) + 3e- → Al(s)","Anode: 2O2-(l) → O2(g) + 4e-"}',
  '[{"issue":"Hot surface burns during the process.","effect":"Wounds and pain to workers.","mitigation":"Proper use of PPE."},{"issue":"Poisonous waste gas fumes.","effect":"Respiratory disorders.","mitigation":"Fit catalytic converters in exhaust pipes."}]'::jsonb, '{"Employment opportunities → increased income → improved standards of living"}', '[{"front":"What is the principal ore of aluminium?","back":"Bauxite."},{"front":"Why is aluminium oxide dissolved in molten cryolite?","back":"To lower its melting point from ~2000°C to about 800°C, saving energy."},{"front":"What happens at the cathode during aluminium electrolysis?","back":"Al3+ ions gain electrons and are deposited as molten aluminium metal."},{"front":"What happens at the anode during aluminium electrolysis?","back":"O2- ions lose electrons and are released as oxygen gas."},{"front":"What electrodes are used in aluminium electrolysis?","back":"Graphite electrodes."}]'::jsonb, '{}'::jsonb
)
on conflict (id) do update set
  subject_id = excluded.subject_id, day = excluded.day, title = excluded.title,
  token_reward_base = excluded.token_reward_base, raw_materials = excluded.raw_materials,
  steps = excluded.steps, equations = excluded.equations, side_effects = excluded.side_effects,
  social_benefits = excluded.social_benefits, flashcards = excluded.flashcards, content = excluded.content;

delete from quiz_questions where topic_id = 'aluminium';

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'aluminium', 'What is the principal ore from which aluminium is extracted?', 'multiple_choice',
  '{"Haematite","Bauxite","Copper pyrites","Galena"}', 1,
  null, null, 'Bauxite is purified via the Bayer process to obtain pure aluminium oxide.'
);

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'aluminium', 'Why is aluminium oxide dissolved in molten cryolite before electrolysis?', 'multiple_choice',
  '{"To make it conduct electricity for the first time","To lower its melting point and save energy","To remove iron impurities","To increase its density"}', 1,
  null, null, 'Pure Al2O3 melts around 2000°C; dissolving it in cryolite lowers this to about 800°C.'
);

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'aluminium', 'During electrolysis of molten aluminium oxide, what happens at the cathode?', 'multiple_choice',
  '{"Oxygen gas is released","Aluminium ions are reduced to aluminium metal","Cryolite is decomposed","Graphite is deposited"}', 1,
  null, null, 'Al3+(l) + 3e- → Al(s) — reduction occurs at the cathode.'
);

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'aluminium', 'What gas is produced at the anode during aluminium extraction?', 'multiple_choice',
  '{"Hydrogen","Chlorine","Oxygen","Carbon dioxide only"}', 2,
  null, null, '2O2-(l) → O2(g) + 4e- at the anode.'
);

insert into topics (id, subject_id, day, title, token_reward_base, raw_materials, steps, equations, side_effects, social_benefits, flashcards, content) values (
  'cement', 'chemistry', 5, 'Manufacture of Cement', 5,
  '{"Limestone","Clay","Water","Gypsum"}', '{"Limestone and clay are crushed and milled into fine powder.","The powder is mixed with water and fed into a rotating cylinder, heated to about 1500°C.","Limestone decomposes to calcium oxide and carbon dioxide.","Calcium oxide reacts with aluminium oxide and silicon dioxide in clay to form lumps of calcium aluminate and calcium silicate.","The lumps are crushed to form cement as a fine powder.","Gypsum is added during grinding to moderate the reaction between cement and water.","Cement is packed in bags for use."}', '{"CaCO3(s) → CaO(s) + CO2(g)"}',
  '[{"issue":"Toxic gases and dust released to the atmosphere.","effect":"Respiratory complications.","mitigation":"Fit scrubbers in exhaust pipes to neutralise toxic gases."},{"issue":"Destruction of vegetation for plant construction.","effect":"Increased CO2, global warming.","mitigation":"Plant fast-growing, fast-maturing trees."},{"issue":"Hot surface burns from combustion process.","effect":"Wounds and pain to workers.","mitigation":"Proper use of PPE."}]'::jsonb, '{"Employment → increased income → improved standards of living","Government revenue → roads, schools, hospitals"}', '[{"front":"What is added during grinding to moderate cement''s reaction with water?","back":"Gypsum."},{"front":"At roughly what temperature is the limestone/clay mixture heated?","back":"About 1500°C."},{"front":"What does limestone decompose into when heated?","back":"Calcium oxide and carbon dioxide."}]'::jsonb, '{}'::jsonb
)
on conflict (id) do update set
  subject_id = excluded.subject_id, day = excluded.day, title = excluded.title,
  token_reward_base = excluded.token_reward_base, raw_materials = excluded.raw_materials,
  steps = excluded.steps, equations = excluded.equations, side_effects = excluded.side_effects,
  social_benefits = excluded.social_benefits, flashcards = excluded.flashcards, content = excluded.content;

delete from quiz_questions where topic_id = 'cement';

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'cement', 'Why is gypsum added during the grinding of cement clinker?', 'multiple_choice',
  '{"To colour the cement","To moderate the reaction between cement and water","To increase the melting point","To act as a catalyst"}', 1,
  null, null, 'Gypsum controls the setting time of cement when mixed with water.'
);

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'cement', 'The main raw materials for cement manufacture are:', 'multiple_choice',
  '{"Bauxite and cryolite","Limestone and clay","Copper pyrites and silica","Haematite and coke"}', 1,
  null, null, 'Limestone and clay are crushed, milled, and heated together to form cement clinker.'
);

insert into topics (id, subject_id, day, title, token_reward_base, raw_materials, steps, equations, side_effects, social_benefits, flashcards, content) values (
  'ammonium-nitrate', 'chemistry', 6, 'Manufacture of Ammonium Nitrate Fertilizer', 5,
  '{"Nitrogen (from air)","Hydrogen (from natural gas)","Iron catalyst","Platinum catalyst","Ammonia"}', '{"Nitrogen from air and hydrogen from natural gas are compressed and passed over heated iron catalyst to form ammonia.","Ammonia is mixed with excess oxygen, purified, and passed over a platinum catalyst at 700°C, oxidising it to nitrogen monoxide and water.","The gases are cooled and mixed with more air to form nitrogen dioxide.","Nitrogen dioxide is absorbed in hot water with excess oxygen to form nitric acid in the absorption tower.","Nitric acid is reacted with concentrated ammonia to form ammonium nitrate.","The product is evaporated to dryness to obtain pure ammonium nitrate."}', '{"N2(g) + 3H2(g) ⇌ 2NH3(g) [Fe catalyst]","4NH3(g) + 5O2(g) → 4NO(g) + 6H2O(g) [Pt catalyst, 700°C]","NH3 + HNO3 → NH4NO3"}',
  '[{"issue":"Toxic acidic gases released to the atmosphere.","effect":"Acid rain, lowering soil pH and reducing crop yields.","mitigation":"Fit catalytic converters to convert nitrogen oxides to nitrogen."},{"issue":"Toxic gases released to the atmosphere.","effect":"Respiratory complications.","mitigation":"Fit scrubbers in exhaust pipes."},{"issue":"Destruction of vegetation for plant construction.","effect":"Increased CO2, global warming.","mitigation":"Plant fast-growing, fast-maturing trees."}]'::jsonb, '{"Employment → increased income → improved standards of living","Government revenue → roads → facilitates trade"}', '[{"front":"What catalyst is used to make ammonia from nitrogen and hydrogen?","back":"Heated iron catalyst."},{"front":"What catalyst oxidises ammonia to nitrogen monoxide?","back":"Platinum, at about 700°C."},{"front":"What acid is formed when nitrogen dioxide is absorbed in hot water and oxygen?","back":"Nitric acid."},{"front":"What is formed when nitric acid reacts with ammonia?","back":"Ammonium nitrate."}]'::jsonb, '{}'::jsonb
)
on conflict (id) do update set
  subject_id = excluded.subject_id, day = excluded.day, title = excluded.title,
  token_reward_base = excluded.token_reward_base, raw_materials = excluded.raw_materials,
  steps = excluded.steps, equations = excluded.equations, side_effects = excluded.side_effects,
  social_benefits = excluded.social_benefits, flashcards = excluded.flashcards, content = excluded.content;

delete from quiz_questions where topic_id = 'ammonium-nitrate';

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'ammonium-nitrate', 'Which catalyst is used to combine nitrogen and hydrogen into ammonia?', 'multiple_choice',
  '{"Platinum","Vanadium(V) oxide","Iron","Nickel"}', 2,
  null, null, 'N2 + 3H2 ⇌ 2NH3 over a heated iron catalyst.'
);

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'ammonium-nitrate', 'At which stage is a platinum catalyst used in this process?', 'multiple_choice',
  '{"Combining nitrogen and hydrogen","Oxidising ammonia to nitrogen monoxide","Forming ammonium nitrate","Evaporating the final product"}', 1,
  null, null, '4NH3 + 5O2 → 4NO + 6H2O, over platinum at ~700°C.'
);

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'ammonium-nitrate', 'What is the final product of reacting nitric acid with ammonia?', 'multiple_choice',
  '{"Sodium nitrate","Ammonium nitrate","Ammonium sulphate","Urea"}', 1,
  null, null, 'NH3 + HNO3 → NH4NO3, evaporated to dryness to obtain the pure fertilizer.'
);

insert into topics (id, subject_id, day, title, token_reward_base, raw_materials, steps, equations, side_effects, social_benefits, flashcards, content) values (
  'biogas', 'chemistry', 7, 'Manufacture of Biogas', 5,
  '{"Organic waste","Water","Anaerobic bacteria"}', '{"Organic wastes are put into a tank and mixed with a little water.","The tank is covered to prevent aerial oxidation.","The tank and contents are kept at room temperature for about 2 weeks.","Anaerobic bacteria break down the organic matter to produce biogas.","The biogas is compressed and collected in gas cylinders for storage via pipes."}', '{}',
  '[{"issue":"Explosion of biogas cylinders due to high pressure.","effect":"Can ignite other materials and cause fire.","mitigation":"Keep cylinders in cool areas."},{"issue":"Air pollution by waste gases (hydrogen sulphide, ammonia) from leaks.","effect":"Stomach and respiratory disorders.","mitigation":"Regular maintenance and monitoring of cylinders."},{"issue":"Leakage of hydrogen sulphide.","effect":"Contributes to acid rain, crumbling buildings.","mitigation":"Regular maintenance and monitoring of cylinders."}]'::jsonb, '{"Employment → increased income → improved standards of living","Gas used for lighting and cooking fuel → improved living standards"}', '[{"front":"What breaks down organic matter to produce biogas?","back":"Anaerobic bacteria."},{"front":"Why is the biogas tank covered?","back":"To prevent aerial (air) oxidation."},{"front":"Roughly how long does the biogas tank need to sit at room temperature?","back":"About 2 weeks."},{"front":"Name two toxic gases that can leak from biogas systems.","back":"Hydrogen sulphide and ammonia."}]'::jsonb, '{}'::jsonb
)
on conflict (id) do update set
  subject_id = excluded.subject_id, day = excluded.day, title = excluded.title,
  token_reward_base = excluded.token_reward_base, raw_materials = excluded.raw_materials,
  steps = excluded.steps, equations = excluded.equations, side_effects = excluded.side_effects,
  social_benefits = excluded.social_benefits, flashcards = excluded.flashcards, content = excluded.content;

delete from quiz_questions where topic_id = 'biogas';

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'biogas', 'What organisms break down organic waste to produce biogas?', 'multiple_choice',
  '{"Aerobic fungi","Anaerobic bacteria","Yeast","Algae"}', 1,
  null, null, 'Anaerobic bacteria decompose organic matter in the absence of air to produce biogas.'
);

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'biogas', 'Why is the biogas digester tank kept covered?', 'multiple_choice',
  '{"To keep it warm only","To prevent aerial oxidation","To speed up combustion","To let sunlight in"}', 1,
  null, null, 'Covering prevents air from entering, maintaining the anaerobic conditions bacteria need.'
);

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'biogas', 'A toxic gas that can leak from biogas systems and contribute to acid rain is:', 'multiple_choice',
  '{"Nitrogen","Hydrogen sulphide","Argon","Oxygen"}', 1,
  null, null, 'Hydrogen sulphide leakage can cause acid rain and crumbling of buildings.'
);

insert into topics (id, subject_id, day, title, token_reward_base, raw_materials, steps, equations, side_effects, social_benefits, flashcards, content) values (
  'naoh-chlorine', 'chemistry', 7, 'Manufacture of Sodium Hydroxide and Chlorine', 5,
  '{"Brine (concentrated sodium chloride solution)","Mercury (cathode)","Graphite (anode)"}', '{"Brine is electrolysed in an electrolytic cell with a mercury cathode and graphite anode.","Chloride ions move to the anode, are discharged, and lose electrons to form chlorine gas (due to high concentration).","Chlorine gas is dried, liquefied, and stored in tightly closed tanks.","Sodium and hydrogen ions move to the cathode; sodium ions are discharged, gaining electrons to form sodium metal.","Sodium metal dissolves in mercury to form sodium amalgam.","Sodium amalgam reacts with water to form sodium hydroxide solution, hydrogen, and mercury (mercury is recycled to the cathode).","The sodium hydroxide solution is evaporated to dryness, then cooled to form solid sodium hydroxide."}', '{"At anode: 2Cl-(aq) → Cl2(g) + 2e-","At cathode: Na+ + e- → Na (with Hg) → sodium amalgam","2Na(Hg) + 2H2O → 2NaOH(aq) + H2(g) + 2Hg"}',
  '[{"issue":"Mercury poisoning.","effect":"Damage to nervous system, kidneys, liver, immune system; cancer risk.","mitigation":"Post hazard warning information in working areas."},{"issue":"Toxic acidic gases released to the atmosphere.","effect":"Acid rain, lowering soil pH.","mitigation":"Fit catalytic converters."},{"issue":"Destruction of vegetation for plant construction.","effect":"Increased CO2, global warming.","mitigation":"Plant fast-growing, fast-maturing trees."}]'::jsonb, '{"Employment → increased income → improved standards of living","Government revenue → roads → facilitates trade"}', '[{"front":"What are the cathode and anode materials in this electrolytic cell?","back":"Mercury cathode, graphite anode."},{"front":"What forms at the anode during brine electrolysis?","back":"Chlorine gas."},{"front":"What does sodium form when it dissolves in mercury?","back":"Sodium amalgam."},{"front":"What does sodium amalgam produce when reacted with water?","back":"Sodium hydroxide solution, hydrogen gas, and mercury (recycled)."},{"front":"What is the major health hazard specific to this process?","back":"Mercury poisoning."}]'::jsonb, '{}'::jsonb
)
on conflict (id) do update set
  subject_id = excluded.subject_id, day = excluded.day, title = excluded.title,
  token_reward_base = excluded.token_reward_base, raw_materials = excluded.raw_materials,
  steps = excluded.steps, equations = excluded.equations, side_effects = excluded.side_effects,
  social_benefits = excluded.social_benefits, flashcards = excluded.flashcards, content = excluded.content;

delete from quiz_questions where topic_id = 'naoh-chlorine';

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'naoh-chlorine', 'In the mercury-cathode cell for brine electrolysis, what forms at the graphite anode?', 'multiple_choice',
  '{"Hydrogen gas","Chlorine gas","Sodium metal","Oxygen gas"}', 1,
  null, null, 'Chloride ions are discharged at the anode: 2Cl- → Cl2 + 2e-.'
);

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'naoh-chlorine', 'What does sodium form when it dissolves into the mercury cathode?', 'multiple_choice',
  '{"Sodium hydroxide directly","Sodium amalgam","Sodium chloride","Sodium oxide"}', 1,
  null, null, 'Sodium metal dissolves in mercury to form sodium amalgam, later reacted with water.'
);

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'naoh-chlorine', 'The major specific health hazard of this process, requiring hazard warnings, is:', 'multiple_choice',
  '{"Sulphur dioxide poisoning","Mercury poisoning","Radiation exposure","Carbon monoxide poisoning"}', 1,
  null, null, 'Mercury exposure can damage the nervous system, kidneys, liver, and immune system.'
);

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'naoh-chlorine', 'What three products form when sodium amalgam reacts with water?', 'multiple_choice',
  '{"Sodium hydroxide, hydrogen, and mercury","Sodium chloride, oxygen, and mercury","Sodium oxide, chlorine, and water","Sodium carbonate, hydrogen, and graphite"}', 0,
  null, null, '2Na(Hg) + 2H2O → 2NaOH(aq) + H2(g) + 2Hg, with mercury recycled to the cathode.'
);

insert into subjects (id, title, description, icon, sort_order) values (
  'math', 'Mathematics', 'Trigonometry and geometry — numeric-answer practice.', 'bi-calculator', 1
)
on conflict (id) do update set title = excluded.title, description = excluded.description, icon = excluded.icon, sort_order = excluded.sort_order;

insert into topics (id, subject_id, day, title, token_reward_base, raw_materials, steps, equations, side_effects, social_benefits, flashcards, content) values (
  'trig-ratios', 'math', null, 'Trigonometric Ratios', 5,
  '{}', '{}', '{}',
  '[]'::jsonb, '{}', '[{"front":"sin 30°","back":"1/2"},{"front":"cos 30°","back":"√3/2 ≈ 0.866"},{"front":"tan 45°","back":"1"},{"front":"Which ratio is opposite / adjacent?","back":"tangent (tan)"}]'::jsonb, '{"summary":"The sine, cosine and tangent of an angle in a right-angled triangle, and the exact values for 30°, 45° and 60°.","keyPoints":["sin θ = opposite / hypotenuse","cos θ = adjacent / hypotenuse","tan θ = opposite / adjacent","sin 30° = 1/2, cos 30° = √3/2, tan 30° = 1/√3","sin 45° = cos 45° = 1/√2, tan 45° = 1","sin 60° = √3/2, cos 60° = 1/2, tan 60° = √3"]}'::jsonb
)
on conflict (id) do update set
  subject_id = excluded.subject_id, day = excluded.day, title = excluded.title,
  token_reward_base = excluded.token_reward_base, raw_materials = excluded.raw_materials,
  steps = excluded.steps, equations = excluded.equations, side_effects = excluded.side_effects,
  social_benefits = excluded.social_benefits, flashcards = excluded.flashcards, content = excluded.content;

delete from quiz_questions where topic_id = 'trig-ratios';

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'trig-ratios', 'What is the exact value of sin 30°?', 'numeric',
  null, null,
  0.5, 0.001, 'sin 30° = 1/2 = 0.5 exactly.'
);

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'trig-ratios', 'What is cos 30°? (give a decimal to 3 s.f. or an exact form)', 'numeric',
  null, null,
  0.8660254, 0.01, 'cos 30° = √3/2 ≈ 0.866.'
);

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'trig-ratios', 'In a right-angled triangle, tan θ is defined as:', 'multiple_choice',
  '{"adjacent / hypotenuse","opposite / hypotenuse","opposite / adjacent","hypotenuse / opposite"}', 2,
  null, null, 'tan θ = opposite / adjacent.'
);

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'trig-ratios', 'What is tan 45°?', 'numeric',
  null, null,
  1, 0.001, 'In a 45°–45°–90° triangle opposite = adjacent, so tan 45° = 1.'
);

insert into topics (id, subject_id, day, title, token_reward_base, raw_materials, steps, equations, side_effects, social_benefits, flashcards, content) values (
  'pythagoras', 'math', null, 'Pythagoras'' Theorem', 5,
  '{}', '{}', '{}',
  '[]'::jsonb, '{}', '[{"front":"State Pythagoras'' theorem","back":"a² + b² = c², where c is the hypotenuse"},{"front":"Sides 6 and 8 — what is the hypotenuse?","back":"√(36 + 64) = √100 = 10"}]'::jsonb, '{"summary":"In a right-angled triangle, the square of the hypotenuse equals the sum of the squares of the other two sides: a² + b² = c².","keyPoints":["c is always the hypotenuse (the side opposite the right angle).","To find a shorter side: a = √(c² − b²).","A triangle with sides 3, 4, 5 is right-angled (3² + 4² = 5²)."]}'::jsonb
)
on conflict (id) do update set
  subject_id = excluded.subject_id, day = excluded.day, title = excluded.title,
  token_reward_base = excluded.token_reward_base, raw_materials = excluded.raw_materials,
  steps = excluded.steps, equations = excluded.equations, side_effects = excluded.side_effects,
  social_benefits = excluded.social_benefits, flashcards = excluded.flashcards, content = excluded.content;

delete from quiz_questions where topic_id = 'pythagoras';

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'pythagoras', 'A right-angled triangle has legs of 3 cm and 4 cm. How long is the hypotenuse, in cm?', 'numeric',
  null, null,
  5, 0.001, '√(3² + 4²) = √25 = 5 cm.'
);

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'pythagoras', 'The hypotenuse is 13 and one leg is 5. How long is the other leg?', 'numeric',
  null, null,
  12, 0.001, '√(13² − 5²) = √(169 − 25) = √144 = 12.'
);

insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (
  'pythagoras', 'Which side does c represent in a² + b² = c²?', 'multiple_choice',
  '{"The shortest side","The hypotenuse","Any side","The base"}', 1,
  null, null, 'c is the hypotenuse — the side opposite the right angle.'
);
