// Regenerates supabase/seed.sql from src/lib/quick-solution/data/curriculum.ts.
// curriculum.ts is the single source of truth — never hand-edit seed.sql.
//
// Usage: npm run generate-seed

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { processes } from "../src/lib/quick-solution/data/curriculum";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlTextArray(values: string[]): string {
  const body = values.map((v) => v.replace(/'/g, "''")).join('","');
  return `'{${values.length ? `"${body}"` : ""}}'`;
}

function sqlJsonb(value: unknown): string {
  return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
}

const lines: string[] = [
  "-- ============================================================",
  "-- Generated by scripts/generate-seed.mts — do not hand-edit.",
  "-- Source of truth: src/lib/quick-solution/data/curriculum.ts",
  "-- ============================================================",
  "",
  "truncate table quiz_questions, processes restart identity cascade;",
  "",
];

for (const p of processes) {
  lines.push(
    "insert into processes (id, day, title, raw_materials, steps, equations, side_effects, social_benefits, flashcards) values (",
    `  ${sqlString(p.id)},`,
    `  ${p.day},`,
    `  ${sqlString(p.title)},`,
    `  ${sqlTextArray(p.rawMaterials)},`,
    `  ${sqlTextArray(p.steps)},`,
    `  ${sqlTextArray(p.equations)},`,
    `  ${sqlJsonb(p.sideEffects)},`,
    `  ${sqlTextArray(p.socialBenefits)},`,
    `  ${sqlJsonb(p.flashcards)}`,
    ");",
    ""
  );

  for (const q of p.quiz) {
    lines.push(
      "insert into quiz_questions (process_id, question, options, correct_index, explanation) values (",
      `  ${sqlString(p.id)},`,
      `  ${sqlString(q.question)},`,
      `  ${sqlTextArray(q.options)},`,
      `  ${q.correctIndex},`,
      `  ${sqlString(q.explanation)}`,
      ");",
      ""
    );
  }
}

const outPath = path.join(__dirname, "..", "supabase", "seed.sql");
writeFileSync(outPath, lines.join("\n"));
console.log(`Wrote ${outPath} (${processes.length} processes, ${processes.reduce((n, p) => n + p.quiz.length, 0)} quiz questions).`);
