// Regenerates supabase/seed.sql from the subject modules in src/lib/subjects/*.
// Those modules are the single source of truth — never hand-edit seed.sql.
//
// Usage: npm run generate-seed   (run migrations 002 + 005 first)
//
// Idempotent: subjects/topics upsert by id, quiz questions are replaced per
// topic. Student progress and attempts are never touched.

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { SUBJECT_DEFINITIONS } from "../src/lib/subjects";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Wrap a raw value as a SQL string literal (doubles embedded single quotes).
const lit = (raw: string) => `'${raw.replace(/'/g, "''")}'`;

const s = (v: string | null | undefined) => (v == null ? "null" : lit(v));
const num = (v: number | null | undefined) => (v == null ? "null" : String(v));
const textArray = (values: string[] | undefined) => {
  if (!values || values.length === 0) return "'{}'";
  // Array-literal element quoting: escape backslash then double-quote.
  const inner = values.map((v) => `"${v.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`).join(",");
  return lit(`{${inner}}`);
};
const jsonb = (value: unknown) => lit(JSON.stringify(value ?? {})) + "::jsonb";

const lines: string[] = [
  "-- ============================================================",
  "-- Generated by scripts/generate-seed.mts — do not hand-edit.",
  "-- Source: src/lib/subjects/*",
  "-- ============================================================",
  "",
];

let topicCount = 0;
let questionCount = 0;

SUBJECT_DEFINITIONS.forEach((def, i) => {
  const m = def.meta;
  lines.push(
    "insert into subjects (id, title, description, icon, sort_order) values (",
    `  ${s(m.id)}, ${s(m.title)}, ${s(m.description)}, ${s(m.icon)}, ${i}`,
    ")",
    "on conflict (id) do update set title = excluded.title, description = excluded.description, icon = excluded.icon, sort_order = excluded.sort_order;",
    ""
  );

  for (const t of def.topics) {
    topicCount++;
    lines.push(
      "insert into topics (id, subject_id, day, title, token_reward_base, raw_materials, steps, equations, side_effects, social_benefits, flashcards, content) values (",
      `  ${s(t.id)}, ${s(t.subjectId)}, ${num(t.day)}, ${s(t.title)}, ${t.tokenRewardBase},`,
      `  ${textArray(t.rawMaterials)}, ${textArray(t.steps)}, ${textArray(t.equations)},`,
      `  ${jsonb(t.sideEffects ?? [])}, ${textArray(t.socialBenefits)}, ${jsonb(t.flashcards ?? [])}, ${jsonb(t.content ?? {})}`,
      ")",
      "on conflict (id) do update set",
      "  subject_id = excluded.subject_id, day = excluded.day, title = excluded.title,",
      "  token_reward_base = excluded.token_reward_base, raw_materials = excluded.raw_materials,",
      "  steps = excluded.steps, equations = excluded.equations, side_effects = excluded.side_effects,",
      "  social_benefits = excluded.social_benefits, flashcards = excluded.flashcards, content = excluded.content;",
      "",
      `delete from quiz_questions where topic_id = ${s(t.id)};`,
      ""
    );

    for (const q of t.quiz) {
      questionCount++;
      lines.push(
        "insert into quiz_questions (topic_id, question, question_type, options, correct_index, correct_numeric_value, numeric_tolerance, explanation) values (",
        `  ${s(t.id)}, ${s(q.question)}, ${s(q.type)},`,
        `  ${q.options ? textArray(q.options) : "null"}, ${num(q.correctIndex)},`,
        `  ${num(q.correctNumericValue)}, ${num(q.numericTolerance)}, ${s(q.explanation)}`,
        ");",
        ""
      );
    }
  }
});

const outPath = path.join(__dirname, "..", "supabase", "seed.sql");
writeFileSync(outPath, lines.join("\n"));
console.log(
  `Wrote ${outPath} — ${SUBJECT_DEFINITIONS.length} subjects, ${topicCount} topics, ${questionCount} questions.`
);
